### ISSUE TITLE
Issue in registering SumoEnv-v0 in gym environment

### ISSUE THREAD

**Issue by AimanKhan1997** [liyan2015/SUMO_RL_MobiCharger#1]
I am trying to run the code on [google colab](https://colab.research.google.com/drive/1crCmPl4Evbgg01uV9rcSa6dAxy3aMp3-?usp=sharing). I have followed the steps but still facing the following error as soon as I try to train the environment `!python -m rl_zoo3.train --algo ppo --env SumoEnv-v0 --num-threads 1 --progress --conf-file hyperparams/python/sumoenv_config.py --save-freq 500000 --log-folder /usr/data2/canaltrain_log/ --tensorboard-log /usr/data2/canaltrain_tensorboard/ --verbose 2 --eval-freq 2000000 --eval-episodes 10 --n-eval-envs 10 --vec-env subproc
`
I am getting the following error-
![image](https://github.com/liyan2015/SUMO-RL-MobiCharger/assets/72418210/29af9a94-f5e3-4cbe-940e-c83d9b720363)

I have registered the environment in rl_zoo3/import_envs.py by 
![image](https://github.com/liyan2015/SUMO-RL-MobiCharger/assets/72418210/bff575f7-df18-400c-b9e3-b10cabbf546b)

I have also pasted the code provided on github in exp_manager.py

Kindly let me know if I am doing something wrong.

**Comment by liyan2015** [comment]
Did you install the environment in gym with `pip install -e .`?
Also, there seems to be something wrong with the way you register the environment. Try adding below code after the `rocket_lander_gym`
```
try:
    import canalenv
except ImportError:
    canalenv = None
```

As in [doc](https://rl-baselines3-zoo.readthedocs.io/en/master/guide/custom_env.html), you need to also add below default hyperparameters in `/hyperparameters/ppo.yml` if you need hyper tuning.

```
SumoEnv-v0:
  normalize: true
  n_envs: 22 # 32 # 40 # 25 # 16 # 64 # 68 # 2 # 256 # 144 # number of environment copies running in parallel
  policy: MlpPolicy
  n_timesteps: !!float 1e6
  batch_size: 32 # Number of training minibatches per update
  n_steps: 128 # batch size is n_steps * n_env
  gamma: 0.99
  learning_rate: 5.0e-4 # The learning rate, it can be a function
  ent_coef: 0.0 # Entropy coefficient for the loss caculation
  clip_range: 0.2 # Clipping parameter, it can be a function
  n_epochs: 10 #  Number of epoch when optimizing the surrogate
  gae_lambda: 0.95 #  Factor for trade-off of bias vs variance for Generalized Advantage Estimator
  max_grad_norm: 1
  vf_coef: 0.871923
```
Your issue is basically the same as in [here](https://stackoverflow.com/questions/67628686/what-is-missing-in-openai-gym-registration)
